/*
 * STEPPER_configuration.h
 *
 *  Created on: Aug 10, 2022
 *      Author: Mario Ezzat
 */

#ifndef INCLUDE_HAL_STEPPER_STEPPER_CONFIGURATION_H_
#define INCLUDE_HAL_STEPPER_STEPPER_CONFIGURATION_H_

#define STEPPER_PORT PORTA

#define  STEPPER_PIN1 PIN0
#define  STEPPER_PIN2 PIN1
#define  STEPPER_PIN3 PIN2
#define  STEPPER_PIN4 PIN3

#define STEPPER_ANGLE 5.23

#endif /* INCLUDE_HAL_STEPPER_STEPPER_CONFIGURATION_H_ */
