/*
 * USART_configuration.h
 *
 *  Created on: Aug 24, 2022
 *      Author: Mario Ezzat
 */

#ifndef INCLUDE_MCAL_USART_USART_CONFIGURATION_H_
#define INCLUDE_MCAL_USART_USART_CONFIGURATION_H_

#define F_CPU 8000000UL
#define BOUDRATE 9600

/*SPEED:- DOUBLE_SPEED_OFF - DOUBLE_SPEED_ON*/
#define USART_DOUBLE_SPEED DOUBLE_SPEED_OFF

/* MODE_OF_OPERATION :- ASYNCHRONOUS - SYNCHRONOUS */
#define MODE_OF_OPERATION	ASYNCHRONOUS

/*INTERRUPTS :- INTERRUPT_DISABLE - INTERRUPT_ENABLE*/
#define USART_TX_INTERRUPT_MODE				INTERRUPT_DISABLE
#define USART_RX_INTERRUPT_MODE			 	INTERRUPT_DISABLE
#define USART_DATA_REGISTER_INTERRUPT_MODE	INTERRUPT_DISABLE

/*PARITY_MODE :- PARITY_DISABLE - PARITY_EVEN - PARITY_ODD */
#define PARITY_MODE PARITY_DISABLE

/*DATA SIZE :- 5 --> 9 bits */
#define CHARACTER_SIZE CHAR_EIGHT_BIT

/*STOP_BITS_MODE :- ONE_STOP_BIT - TWO_STOP_BIT*/
#define STOP_BITS_MODE ONE_STOP_BIT

/*time for non blockin*/
#define TIME_OUT 500000


#endif /* INCLUDE_MCAL_USART_USART_CONFIGURATION_H_ */
